openapi: 3.0.1
info:
  title: HTTP bin
  description: First API Manualmente
  version: '1.0'
servers:
  - url: https://apim-cogonzalez.azure-api.net/httpbin
paths:
  /get:
    get:
      summary: FetchData
      description: FetchData
      operationId: fetchdata
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]